on: [push, pull_request]
name: PHP CS Fixer
jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.18.5
              with:
                  args: --config=./web/.php-cs-fixer.php --diff --dry-run
